package com.zanderwohl.chunks.Delta;

import java.io.Serializable;

/**
 * Tells a client that communication is about to cease.
 * Client should clean up its network things when it receives this.
 */
public class Kick extends Delta implements Serializable {

    private static final long serialVersionUID = 32112000003L;

    public final String reason;

    /**
     * An delta that kicks a player form a server.
     * @param reason The reason the player was kicked. Either given by an admin or autogenerated by the server.
     */
    public Kick(String reason) {
        this.reason = reason;
    }

}
